# (*) for mandatory configurations, and ($) for default values
date-config:
  date-pattern: "yyyy-MM-dd"
  time-pattern: "HH:mm:ss"
  date-time-pattern: "yyyy-MM-dd HH:mm:ss"
  zoned-date-time-pattern: "yyyy-MM-dd HH:mm:ss Z"

environments:
  - local
  - test


gui:
  # (*) chrome, firefox, edge
  browser: chrome
  base-url: https://the-internet.herokuapp.com/
  options:
    # maximized ($) or provide a size like 1920,1080
    screen-size: maximized
    # ture ($), false
    headless: false
    # NORMAL ($), EAGER, NONE
    page-Loading-strategy: NORMAL
    # list of optional arguments
    arguments:
      - --remote-allow-origins=*

  timeouts:
    # 30 ($) in seconds
    page-load-timeout: 30